steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
  - name: veracode/pipeline-scan:latest
   entrypoint: 'bash'
   args: ['-c', 'java -jar /opt/veracode/pipeline-scan.jar --veracode_api_id "$${VERACODE_ID}" --veracode_api_key "$${VERACODE_KEY}" --fail_on_severity="Very High, High" --file "./target/verademo.war"']
   secretEnv: ['VERACODE_ID', 'VERACODE_KEY']
#   - name: veracode/api-wrapper-java:latest
#     entrypoint: 'bash'
#     args: [ '-c', 'java -jar /opt/veracode/api-wrapper.jar -vid "$${VERACODE_ID}" -vkey "$${VERACODE_KEY}" -action UploadAndScan -createprofile true -appname ${REPO_NAME} -version "${SHORT_SHA}_$(date +%F_%H:%M:%S)" -sandboxname "gcp testing" -createsandbox true  -scantimeout 30 -filepath ./target/verademo.war' ]
#     secretEnv: [ 'VERACODE_ID', 'VERACODE_KEY' ]
timeout: 900s
availableSecrets:
  secretManager:
    - versionName: projects/864317778079/secrets/VERACODE_ID/versions/latest
      env: 'VERACODE_ID'
    - versionName: projects/864317778079/secrets/VERACODE_KEY/versions/latest
      env: 'VERACODE_KEY'
